### ISSUE TITLE
AI-GCS: Design and implement core fingerprinting and content-defined chunking algorithms

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/ai-gen-code-search#1]
This about the design and implementation of a core fingerprinting algorithm to
support approximate matching in hamming distance, and a
content-defined chunking algorithm to break code in location-
independent and content-defined chunks. 

The result is the a design document, the submission of a defensive publication to TDcommons.org (for patent protection), and creation of a library that implements the core algorithms.

- [x] Create and submit defensive publication to TDcommons.org (for patent protection)
- [x] Create and document design 
- [x] Create initial open source library for fingerprinting

**Comment by JonoYang** [comment]
We have implemented the halohash algorithm for file fingerprinting use at https://github.com/aboutcode-org/matchcode-toolkit. We also have snippets, which are hash digest values of ngrams that have been hashed into a BitAveragedHaloHash. The ngrams of a file are selected using the hailstorm algorithm (https://github.com/aboutcode-org/scancode-toolkit/blob/develop/src/licensedcode/tokenize.py#L313) and has been added to the matchcode-toolkit repo (https://github.com/aboutcode-org/matchcode-toolkit/pull/12)

**Comment by JonoYang** [comment]
matchcode-toolkit 6.0.1 has been release on pypi (https://pypi.org/project/matchcode-toolkit/) where we now collect snippet fingerprints for finer content matching.

**Comment by pombredanne** [comment]
- Thedefensive publication at tdcommons.org titled: "Method for Approximate Content Discovery" has been accepted and is live at: https://www.tdcommons.org/dpubs_series/7579/
  - The source and PDF documents for the publication are also published at: https://github.com/aboutcode-org/ai-gen-code-search/tree/main/docs/references
- The design document for the approach for content chunking and fingerprinting has been published at https://github.com/aboutcode-org/ai-gen-code-search/blob/main/docs/source/approximate-matching-design-1.rst We also published this as part of the project documentation at https://ai-gen-code-search.readthedocs.io/
- An initial library is tagged at https://github.com/aboutcode-org/matchcode-toolkit/releases/tag/v6.0.0
  - The code is deployed at:
    - https://github.com/aboutcode-org/matchcode-toolkit/ for integration in ScanCode and MatchCode
    - Here in https://github.com/aboutcode-org/ai-gen-code-searc/src for standalone and general purpose reuse and integration in other tools

**Comment by pombredanne** [comment]
Closing now!
