### ISSUE TITLE
AI-GCS: Package algorithms in a reusable library

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/ai-gen-code-search#2]
Package and release the library (on PyPI) for reuse and integration in other tools.
- [x] Tag and release the library that implements the core algorithms
- [x] Create and publish library documentation

**Comment by JonoYang** [comment]
The halohash algorithm and fingerprinting functions are available in matchcode toolkit. https://pypi.org/project/matchcode-toolkit/

**Comment by pombredanne** [comment]
We also have https://pypi.org/project/samecode/ for the barebones library. The doc for this library is published now at https://ai-gen-code-search.readthedocs.io/en/latest/
